public class Aula003_NumerosPrimitivos {
    // int...int recebe apénas números inteiros...
    int idade = 10;
    // double...double recebe números inteiros e quebrados...
    double salario = 2000.00;
    // boolean...boolean recebe dois parametros 'true' e 'false', true = verdadeiro e false = falso...
    boolean verdade = true; 
    boolean falso = false;
    // String...String recebe nomes e texto em geral...
    String texto = "Igor";
}
